// frontend/src/pages/Home.jsx
//import React from "react";
import Carousel from 'react-bootstrap/Carousel';
import img4 from '../images/img4.jpg';
import img5 from '../images/img5.jpg';
import img6 from '../images/img6.jpg';
import '../design/HomePageStyle.css';

const Home = () => {
    return (<div>
            <Carousel>
                <Carousel.Item>
                    <img
                        style={{objectFit: 'cover', width: '100%', maxHeight: '100vh'}}
                        className="d-block w-100"
                        src={img4}
                        alt="First slide"
                    />
                    <Carousel.Caption style={{color: 'black', textShadow: '1px 1px 2px white'}}>
                        <h3>“People who love to eat are always the best people.”</h3>
                        <p>Julia Child</p>
                    </Carousel.Caption>
                </Carousel.Item>
                <Carousel.Item>
                    <img
                        style={{objectFit: 'cover', width: '100%', maxHeight: '100vh'}}
                        className="d-block w-100"
                        src={img5}
                        alt="Second slide"
                    />
                    <Carousel.Caption style={{color: 'black', textShadow: '1px 1px 2px white'}}>
                        <h3>“People who love to eat are always the best people.”</h3>
                        <p>Julia Child</p>
                    </Carousel.Caption>
                </Carousel.Item>
                <Carousel.Item>
                    <img
                        style={{objectFit: 'cover', width: '100%', maxHeight: '100vh'}}
                        className="d-block w-100"
                        src={img6}
                        alt="Third slide"
                    />
                    <Carousel.Caption style={{color: 'black', textShadow: '1px 1px 2px white'}}>
                        <h3>“People who love to eat are always the best people.”</h3>
                        <p>Julia Child</p>
                    </Carousel.Caption>
                </Carousel.Item>
            </Carousel>
        </div>)
}

export default Home;

// frontend-angular/src/app/home/home.component.ts
import {Component, ViewChild} from '@angular/core';
import {NgbCarousel} from '@ng-bootstrap/ng-bootstrap';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent {
  paused = false;

  @ViewChild('carousel', {static: true})
  carousel!: NgbCarousel;

  togglePaused() {
    this.paused = !this.paused;
    if (this.paused) {
      this.carousel.pause();
    } else {
      this.carousel.cycle();
    }
  }
}

<ngb-carousel #carousel [interval]="3000" (mouseenter)="togglePaused()" (mouseleave)="togglePaused()" class="carousel-container">
  <ng-template ngbSlide>
    <img src="assets/img4.jpg" class="d-block w-100 carousel-img" alt="1">
    <div class="carousel-caption d-none d-md-block">
      <h5>“People who love to eat are always the best people.”</h5>
      <p>Julia Child</p>
    </div>
  </ng-template>
  <ng-template ngbSlide>
    <img src="assets/img5.jpg" class="d-block w-100 carousel-img" alt="2">
    <div class="carousel-caption d-none d-md-block">
      <h5>“People who love to eat are always the best people.”</h5>
      <p>Julia Child</p>
    </div>
  </ng-template>
  <ng-template ngbSlide>
    <img src="assets/img6.jpg" class="d-block w-100 carousel-img" alt="3">
    <div class="carousel-caption d-none d-md-block">
      <h5>“People who love to eat are always the best people.”</h5>
      <p>Julia Child</p>
    </div>
  </ng-template>
</ngb-carousel>
