// frontend-angular/src/app/openfridge/openfridge.component.ts
import { Component, Inject, OnInit, PLATFORM_ID } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { isPlatformBrowser } from '@angular/common';

@Component({
  selector: 'app-open-fridge',
  templateUrl: './openfridge.component.html',
  styleUrls: ['./openfridge.component.css']
})
export class OpenFridgeComponent implements OnInit {
  fridgeItems: any[] = [];
  newItemName: string = '';
  newItemQuantity: number | null = null;
  selectedItemId: number | null = null;
  updatedItemName: string = '';
  showUpdateField: boolean = false;
  searchTerm: string = '';
  member: any = null;
  filteredFridgeItems: any[] = [];

  constructor(
    @Inject(PLATFORM_ID) private platformId: Object,
    private http: HttpClient
  ) { }

  ngOnInit(): void {
    if (isPlatformBrowser(this.platformId)) {
      const token = localStorage.getItem('token');
      this.fetchAllFridgeItems();
      this.fetchMember();
    }
  }

  fetchMember(): void {
    const token = localStorage.getItem('token');
    const name = localStorage.getItem('username');
    this.http.get<any>(`/api/member/${name}/fridgeId`, {
      headers: {
        Authorization: `Bearer ${token}`,
      },
    })
    .subscribe(response => {
      this.member = response;
    }, error => {
      console.error('Error fetching member:', error);
    });
  }
  
  fetchAllFridgeItems(): void {
    const token = localStorage.getItem('token');
    this.http.get<any[]>('/api/fridgeItems', {
      headers: {
        Authorization: `Bearer ${token}`,
      },
    })
    .subscribe(response => {
      this.fridgeItems = response;
      this.filteredFridgeItems = response;
    }, error => {
      console.error('Error fetching fridge items:', error);
    });
  }

  addFridgeItem(): void {
    const token = localStorage.getItem('token');
    this.http.post<any>('/api/fridgeItem', {
      name: this.newItemName,
      quantity: this.newItemQuantity,
      fridge: this.member.fridge,
    }, {
      headers: {
        Authorization: `Bearer ${token}`,
      },
    })
    .subscribe(response => {
      this.newItemName = '';
      this.newItemQuantity = null;
      this.fetchAllFridgeItems();
    }, error => {
      console.error('Error adding fridge item:', error);
    });
  }

  updateItem(item: any): void {
    this.selectedItemId = item.id;
    this.showUpdateField = true;
    this.updatedItemName = item.name;
    this.newItemQuantity = item.quantity;
  }

  confirmUpdate(): void {
    const token = localStorage.getItem('token');
    const updatedItem = {
      id: this.selectedItemId,
      name: this.updatedItemName,
      quantity: this.newItemQuantity
    };
    this.http.put<any>('/api/update', updatedItem, {
      headers: {
        Authorization: `Bearer ${token}`,
      },
    })
    .subscribe(response => {
      this.showUpdateField = false;
      this.fetchAllFridgeItems();
    }, error => {
      console.error('Error updating fridge item:', error);
    });
  }

  cancelUpdate(): void {
    this.showUpdateField = false;
  }
  
  deleteFridgeItem(id: number): void {
    const token = localStorage.getItem('token');
    this.http.delete(`/api/delete/${id}`, {
      headers: {
        Authorization: `Bearer ${token}`,
      },
      responseType: 'text'
    })
    .subscribe(response => {
      if (response === `Item removed !${id}`) {
        this.fetchAllFridgeItems();
      } else {
        console.error('Unexpected response when deleting fridge item:', response);
      }
    }, error => {
      console.error('Error deleting fridge item:', error);
      console.log('Full error object:', error);
    });
  } 

  filterItems(): void {
    if (!this.searchTerm.trim()) {
      this.filteredFridgeItems = this.fridgeItems;
    } else {
      this.filteredFridgeItems = this.fridgeItems.filter(item =>
        item.name.toLowerCase().includes(this.searchTerm.toLowerCase())
      );
    }
  }
}

<div class="card-container">
  <div class="card">
    <h2 class="card-header">My Items</h2>

    <input type="text" placeholder="Search items..." [(ngModel)]="searchTerm" (input)="filterItems()">

    <div *ngFor="let item of filteredFridgeItems" class="item-card">
      <div class="item-content">
        <p>{{ item.name }} - Quantity: {{ item.quantity }}</p>
        <div *ngIf="selectedItemId !== item.id || !showUpdateField">
          <button (click)="updateItem(item)">Update Item</button>
        </div>
        <button (click)="deleteFridgeItem(item.id)">Delete</button>
      </div>

      <div *ngIf="selectedItemId === item.id && showUpdateField" class="update-item-card">
        <h3>Update Item</h3>
        <label for="updatedItemName">New Name:</label>
        <input type="text" id="updatedItemName" [(ngModel)]="updatedItemName" name="updatedItemName">
        <label for="newItemQuantity">New Quantity:</label>
        <input type="number" id="newItemQuantity" [(ngModel)]="newItemQuantity" name="newItemQuantity">
        <div>
          <button (click)="confirmUpdate()">Confirm Update</button>
          <button (click)="cancelUpdate()">Cancel</button>
        </div>
      </div>
    </div>

    <h2 class="card-header">Add New Item</h2>
    <form (submit)="addFridgeItem()">
      <label for="itemName">Name:</label>
      <input type="text" id="itemName" [(ngModel)]="newItemName" name="itemName" required>
      <label for="itemQuantity">Quantity:</label>
      <input type="number" id="itemQuantity" [(ngModel)]="newItemQuantity" name="itemQuantity" required>
      <button type="submit">Add Item</button>
    </form>
  </div>
</div>

// frontend/src/pages/OpenFridge.jsx
import React, { useState, useEffect } from 'react';
import axios from 'axios';
import {
    Button,
    Card,
    Col,
    Container,
    Form,
    FormControl,
    InputGroup,
    Row,
} from 'react-bootstrap';
import {useAuth} from "../components/AuthContext.jsx";
import data from "bootstrap/js/src/dom/data.js";

const OpenFridge = () => {
    const [fridgeItems, setFridgeItems] = useState([]);
    const [newItemName, setNewItemName] = useState('');
    const [selectedItemId, setSelectedItemId] = useState(null);
    const [updatedItemName, setUpdatedItemName] = useState('');
    const [showUpdateField, setShowUpdateField] = useState(false);
    const [searchTerm, setSearchTerm] = useState('');
    const [newItemQuantity, setNewItemQuantity] = useState(1);
    const [member, setMember] = useState(null);
    const { logout } = useAuth();

    useEffect(() => {
        fetchAllFridgeItems();
        fetchMember();
    }, []);


    const fetchMember = () => {
        const token = localStorage.getItem('token');
        const name = localStorage.getItem('username');
        console.log(name);
        axios
            .get(`/api/member/${name}/fridgeId`, {
                headers: {
                    Authorization: `Bearer ${token}`,
                },
            })
            .then((response) => setMember(response.data))
            .catch((error) => {
                if (error.response && error.response.status === 401) {
                    logout();
                }
                console.error('Error fetching fridge items', error);
            });
    };


    const fetchAllFridgeItems = () => {
        const token = localStorage.getItem('token');
        axios
            .get('/api/fridgeItems', {
                headers: {
                    Authorization: `Bearer ${token}`,
                },
            })
            .then((response) => setFridgeItems(response.data))
            .catch((error) => {
                if (error.response && error.response.status === 401) {
                    logout();
                }
                console.error('Error fetching fridge items', error);
            });
    };

    const handleAddItem = () => {
        const token = localStorage.getItem('token');
        axios
            .post(
                '/api/fridgeItem',
                {
                    name: newItemName,
                    quantity: newItemQuantity,
                    fridge: member.fridge,
                },
                {
                    headers: {
                        Authorization: `Bearer ${token}`,
                    },
                }
            )
            .then((response) => {
                setNewItemName('');
                setNewItemQuantity(1);
                fetchAllFridgeItems();
            })
            .catch((error) => console.error('Error adding fridge item', error));
    };

    const handleUpdateItem = (id) => {
        setSelectedItemId(id);
        setShowUpdateField(true);
    };

    const handleConfirmUpdate = () => {
        const selectedItem = fridgeItems.find((item) => item.id === selectedItemId);

        if (selectedItem) {
            const updatedItem = {
                id: selectedItem.id,
                name: updatedItemName || selectedItem.name,
                quantity: newItemQuantity || selectedItem.quantity,
            };

            const token = localStorage.getItem('token');
            axios
                .put('/api/update', updatedItem, {
                    headers: {
                        Authorization: `Bearer ${token}`,
                    },
                })
                .then((response) => {
                    setUpdatedItemName('');
                    setNewItemQuantity(1);
                    setShowUpdateField(false);
                    fetchAllFridgeItems();
                })
                .catch((error) => console.error('Error updating fridge item', error));
        } else {
            console.error('Selected item not found');
        }
    };

    const handleCancelUpdate = () => {
        setShowUpdateField(false);
    };

    const handleDeleteItem = (id) => {
        const token = localStorage.getItem('token');
        axios
            .delete(`/api/delete/${id}`, {
                headers: {
                    Authorization: `Bearer ${token}`,
                },
            })
            .then((response) => fetchAllFridgeItems())
            .catch((error) => console.error('Error deleting fridge item', error));
    };

    const filteredFridgeItems = fridgeItems.filter((item) =>
        item.name.toLowerCase().includes(searchTerm.toLowerCase())
    );

    return (
        <Container className="p-3 mt-5" style={{ backgroundColor: '#f8f9fa', minHeight: '100vh' }}>
            <h2 className="text-center mb-4" style={{ color: '#007bff' }}>
                Fridge Management
            </h2>

            <InputGroup className="mb-3">
                <FormControl
                    type="text"
                    placeholder="Search Item"
                    value={searchTerm}
                    onChange={(e) => setSearchTerm(e.target.value)}
                />
            </InputGroup>

            <Row xs={1} md={2} lg={3} className="g-4">
                {filteredFridgeItems.map((item) => (
                    <Col key={item.id} className="mb-3">
                        <Card>
                            <Card.Body>
                                <h5 style={{ color: '#343a40' }}>{item.name}</h5>
                                <p style={{ color: '#6c757d' }}>Quantity: {item.quantity}</p>
                                <div className="d-flex justify-content-between">
                                    <Button variant="info" onClick={() => handleUpdateItem(item.id)}>
                                        Update Item
                                    </Button>
                                    <Button variant="danger" onClick={() => handleDeleteItem(item.id)}>
                                        Delete
                                    </Button>
                                </div>
                            </Card.Body>
                        </Card>
                        {showUpdateField && selectedItemId === item.id && (
                            <Card className="mt-2">
                                <Card.Body>
                                    <Form.Group className="mb-3">
                                        <Form.Control
                                            type="text"
                                            placeholder="New Name"
                                            value={updatedItemName}
                                            onChange={(e) => setUpdatedItemName(e.target.value)}
                                        />
                                    </Form.Group>
                                    <Form.Group className="mb-3">
                                        <Form.Control
                                            type="number"
                                            placeholder="New Quantity"
                                            value={newItemQuantity}
                                            onChange={(e) => setNewItemQuantity(e.target.value)}
                                        />
                                    </Form.Group>
                                    <div className="d-flex justify-content-end">
                                        <Button variant="success" onClick={handleConfirmUpdate}>
                                            OK
                                        </Button>
                                        <Button variant="secondary" className="ms-2" onClick={handleCancelUpdate}>
                                            Cancel
                                        </Button>
                                    </div>
                                </Card.Body>
                            </Card>
                        )}
                    </Col>
                ))}
            </Row>

            <div className="mt-4">
                <h3 style={{ color: '#007bff' }}>Add New Item</h3>
                <InputGroup className="mb-3">
                    <FormControl
                        type="text"
                        placeholder="Item Name"
                        value={newItemName}
                        onChange={(e) => setNewItemName(e.target.value)}
                    />
                </InputGroup>
                <InputGroup className="mb-3">
                    <FormControl
                        type="number"
                        placeholder="Quantity"
                        value={newItemQuantity}
                        onChange={(e) => setNewItemQuantity(e.target.value)}
                    />
                </InputGroup>
                <Button variant="info" onClick={handleAddItem}>
                    Add Item
                </Button>
            </div>
        </Container>
    );
};

export default OpenFridge;
