// frontend-angular/src/app/recipes/recipes.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams } from '@angular/common/http';
import { AuthService } from '../auth.service';

@Component({
  selector: 'app-recipes',
  templateUrl: './recipes.component.html',
  styleUrls: ['./recipes.component.css']
})
export class RecipesComponent implements OnInit {
  ingredients: string = '';
  recipes: any[] = [];
  fridgeItems: any[] = [];
  sortCriteria: string = 'usedIngredientCount';
  sortOrder: string = 'asc';

  constructor(private http: HttpClient, private authService: AuthService) {}

  ngOnInit(): void {
    this.fetchFridgeItems();
  }

  fetchFridgeItems(): void {
    const token = localStorage.getItem('token');
    const headers = new HttpHeaders({
      'Authorization': `Bearer ${token}`
    });

    this.http.get('/api/fridgeItems', { headers })
      .subscribe((data: any) => {
        this.fridgeItems = data;
        const defaultSearchIngredients = this.fridgeItems.map(item => item.name).join(',');
        this.handleSearch(defaultSearchIngredients);
      }, error => {
        console.error(error);
      });
  }

  handleSort(sortOption: string): void {
    const [criteria, order] = sortOption.split('-');
    this.sortCriteria = criteria;
    this.sortOrder = order;
    this.sortRecipes();
  }

  sortRecipes(): void {
    this.recipes.sort((a, b) => {
      const aValue = a[this.sortCriteria];
      const bValue = b[this.sortCriteria];

      if (this.sortOrder === 'asc') {
        return aValue - bValue;
      } else {
        return bValue - aValue;
      }
    });
  }

  handleSearch(searchIngredients: string): void {
    const headers = new HttpHeaders({
      'X-RapidAPI-Key': 'ebc16a25f3mshed55b0ebde53939p1c4784jsnb35adfafdb2e',
      'X-RapidAPI-Host': 'spoonacular-recipe-food-nutrition-v1.p.rapidapi.com'
    });

    const params = new HttpParams()
      .set('ingredients', searchIngredients)
      .set('number', '25')
      .set('ignorePantry', 'true')
      .set('ranking', '1');

    this.http.get('https://spoonacular-recipe-food-nutrition-v1.p.rapidapi.com/recipes/findByIngredients', { headers, params })
      .subscribe((data: any) => {
        this.recipes = data;
        this.sortRecipes();
      }, error => {
        console.error(error);
      });
  }
}

<div class="container-fluid">
  <div class="container mt-5 bg-dark-custom">
    <div class="row mb-3 justify-content-center">
      <div class="col-md-10 d-flex justify-content-center">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Enter ingredients..." [(ngModel)]="ingredients" (keydown.enter)="handleSearch(ingredients)">
          <button class="btn btn-outline-secondary btn-custom ms-2" (click)="handleSearch(ingredients)">Search</button>
          <div class="dropdown ms-2">
            <button class="btn btn-outline-secondary btn-custom dropdown-toggle" type="button" id="sortMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
              Sort By
            </button>
            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="sortMenuButton">
              <li><a class="dropdown-item" (click)="handleSort('usedIngredientCount-asc')">Used Ingredients (Asc)</a></li>
              <li><a class="dropdown-item" (click)="handleSort('usedIngredientCount-desc')">Used Ingredients (Desc)</a></li>
              <li><a class="dropdown-item" (click)="handleSort('missedIngredientCount-asc')">Missed Ingredients (Asc)</a></li>
              <li><a class="dropdown-item" (click)="handleSort('missedIngredientCount-desc')">Missed Ingredients (Desc)</a></li>
              <li><a class="dropdown-item" (click)="handleSort('likes-asc')">Likes (Asc)</a></li>
              <li><a class="dropdown-item" (click)="handleSort('likes-desc')">Likes (Desc)</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div *ngFor="let recipe of recipes" class="col-md-4 mb-4">
        <div class="card card-custom">
          <img class="card-img-top" [src]="recipe.image" [alt]="recipe.title">
          <div class="card-body">
            <h5 class="card-title">{{ recipe.title }}</h5>
            <p class="card-text">
              Used Ingredients: {{ recipe.usedIngredientCount }} <br>
              Missed Ingredients: {{ recipe.missedIngredientCount }} <br>
              Likes: {{ recipe.likes }}
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

// frontend/src/pages/Recipes.jsx
import React, {useEffect, useState} from 'react';
import axios from 'axios';
import {Container, Row, Col, InputGroup, FormControl, Button, Card} from 'react-bootstrap';

const Recipes = () => {
    const [ingredients, setIngredients] = useState('');
    const [recipes, setRecipes] = useState([]);
    const [fridgeItems, setFridgeItems] = useState([]);
    const [sortCriteria, setSortCriteria] = useState('usedIngredientCount');
    const [sortOrder, setSortOrder] = useState('asc');

    useEffect(() => {
        const fetchFridgeItems = async () => {
            try {
                const token = localStorage.getItem('token');
                const response = await axios.get('/api/fridgeitems', {
                    headers: {
                        Authorization: `Bearer ${token}`,
                    },
                });
                setFridgeItems(response.data);
                const defaultSearchIngredients = response.data.map(item => item.name).join(',');
                handleSearch(defaultSearchIngredients);
            } catch (error) {
                console.error(error);
            }
        };

        fetchFridgeItems();
    }, []);

    const handleSort = (criteria) => {
        if (criteria === sortCriteria) {
            setSortOrder(sortOrder === 'asc' ? 'desc' : 'asc');
        } else {
            setSortCriteria(criteria);
            setSortOrder('asc');
        }
    };

    const sortedRecipes = recipes.sort((a, b) => {
        const aValue = a[sortCriteria];
        const bValue = b[sortCriteria];

        if (sortOrder === 'asc') {
            return aValue - bValue;
        } else {
            return bValue - aValue;
        }
    });

    const handleSearch = async (searchIngredients) => {
        try {
            const response = await axios.get('https://spoonacular-recipe-food-nutrition-v1.p.rapidapi.com/recipes/findByIngredients', {
                params: {
                    ingredients: searchIngredients,
                    number: '25',
                    ignorePantry: 'true',
                    ranking: '1',
                },
                headers: {
                    'X-RapidAPI-Key': 'ebc16a25f3mshed55b0ebde53939p1c4784jsnb35adfafdb2e',
                    'X-RapidAPI-Host': 'spoonacular-recipe-food-nutrition-v1.p.rapidapi.com',
                },
            });

            setRecipes(response.data);
        } catch (error) {
            console.error(error);
        }
    };

    return (
        <Container className="mt-5">
            <Row className="mb-3">
                <Col md={8}>
                    <InputGroup className="mb-3">
                        <FormControl
                            placeholder="Enter ingredients..."
                            value={ingredients}
                            onChange={(e) => setIngredients(e.target.value)}
                        />
                        <Button variant="outline-secondary" onClick={() => handleSearch(ingredients)}>
                            Search
                        </Button>
                    </InputGroup>
                </Col>
                <Col md={4} className="d-flex align-items-end">
                    <InputGroup className="mb-2">
                        <InputGroup.Text>Sort By:</InputGroup.Text>
                        <Button
                            variant={`info ${sortCriteria === 'usedIngredientCount' ? 'active' : ''}`}
                            onClick={() => handleSort('usedIngredientCount')}
                        >
                            Used
                        </Button>
                        <Button
                            variant={`info ${sortCriteria === 'missedIngredientCount' ? 'active' : ''}`}
                            onClick={() => handleSort('missedIngredientCount')}
                        >
                            Missed
                        </Button>
                        <Button
                            variant={`info ${sortCriteria === 'likes' ? 'active' : ''}`}
                            onClick={() => handleSort('likes')}
                        >
                            Likes
                        </Button>
                        <Button
                            variant={`info ${sortOrder === 'asc' ? 'active' : ''}`}
                            onClick={() => setSortOrder(sortOrder === 'asc' ? 'desc' : 'asc')}
                        >
                            {sortOrder === 'asc' ? 'Asc' : 'Desc'}
                        </Button>
                    </InputGroup>
                </Col>
            </Row>

            <Row>
                {sortedRecipes.map((recipe) => (
                    <Col key={recipe.id} md={4} className="mb-4">
                        <Card>
                            <Card.Img variant="top" src={recipe.image} alt={recipe.title}/>
                            <Card.Body>
                                <Card.Title>{recipe.title}</Card.Title>
                                <Card.Text>
                                    Used Ingredient Count: {recipe.usedIngredientCount} <br/>
                                    Missed Ingredient Count: {recipe.missedIngredientCount} <br/>
                                    Likes: {recipe.likes}
                                </Card.Text>
                            </Card.Body>
                        </Card>
                    </Col>
                ))}
            </Row>
        </Container>
    );
};

export default Recipes;
