// frontend-angular/src/app/registration/registration.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { HttpClient } from '@angular/common/http';
import { catchError } from 'rxjs/operators';
import { AuthService } from '../auth.service';

@Component({
  selector: 'app-registration',
  templateUrl: './registration.component.html',
  styleUrls: ['./registration.component.css']
})
export class RegistrationComponent {
  registrationForm: FormGroup;
  errorMessage: string = '';

  constructor(
    private router: Router,
    private formBuilder: FormBuilder,
    private http: HttpClient,
    private authService: AuthService
  ) {
    this.registrationForm = this.formBuilder.group({
      username: ['', Validators.required],
      email: ['', [Validators.required, Validators.email]],
      password: ['', Validators.required],
      passwordConfirm: ['', Validators.required]
    });
  }

  handleRegistration() {
    if (this.registrationForm.valid) {
      const { username, email, password } = this.registrationForm.value;
      if (password === this.registrationForm.value.passwordConfirm) {
        const data = { name: username, email: email, password: password };
  
        const jsonData = JSON.stringify(data);
  
        this.http.post<any>('/api/v1/auth/register', jsonData, {
          headers: {
            'Content-Type': 'application/json'
          }
        })
        .pipe(
          catchError(error => {
            console.error(error);
            return error;
          })
        )
    .subscribe(response => {
  if (response && response.error && response.error.token === 'fail') {
    this.errorMessage = 'This username is already in use. Please try another one.';
  } else {
    this.authService.login(response.token, username);
    localStorage.setItem('username', username);
    this.router.navigate(['/home']);
  }
});

      } else {
        alert('Passwords do not match. Please make sure the passwords match.');
      }
    } else {
      alert('Please fill in all required fields.');
    }
  }
}

<div class="registration-container">
<div class="registration-card">
  <h1 class="registration-card-header">Registration</h1>
  <div *ngIf="errorMessage">
    {{ errorMessage }}
    <button type="button" class="close" (click)="errorMessage=''">&times;</button>
  </div>
  <form [formGroup]="registrationForm" (ngSubmit)="handleRegistration()">
    <div class="registration-form-group">
      <label for="username">Username:</label>
      <input type="text" class="form-control" id="username" formControlName="username" required>
    </div>
    <div class="registration-form-group">
      <label for="email">Email:</label>
      <input type="email" class="form-control" id="email" formControlName="email" required>
    </div>
    <div class="registration-form-group">
      <label for="password">Password:</label>
      <input type="password" class="form-control" id="password" formControlName="password" required>
    </div>
    <div class="registration-form-group">
      <label for="passwordConfirm">Confirm Password:</label>
      <input type="password" class="form-control" id="passwordConfirm" formControlName="passwordConfirm" required>
    </div>
    <button type="submit" class="registration-button">Register</button>
  </form>
  <p class="registration-link">
    Already have an account? <a [routerLink]="['/login']">Log In</a>
  </p>
</div>
</div>

// frontend/src/pages/Registration.jsx
import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { useNavigate } from 'react-router-dom';
import Form from 'react-bootstrap/Form';
import Button from 'react-bootstrap/Button';
import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import Alert from 'react-bootstrap/Alert';

function Registration() {
    const [username, setUsername] = useState('');
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [passwordConfirm, setPasswordConfirm] = useState('');
    const [errorMessage, setErrorMessage] = useState('');
    const navigate = useNavigate();
    const [token, setToken] = useState(null);

    const handleRegistration = (e) => {
        e.preventDefault();
        if (password == passwordConfirm) {
            const data = {
                name: username, email: email, password: password
            };
            fetch(`/api/v1/auth/register`, {
                method: 'POST', headers: {
                    'Content-Type': 'application/json',
                }, body: JSON.stringify(data),
            })
                .then((res) => {
                    if (res.ok) {
                        return res.json();
                    } else {
                        throw new Error('Failed to fetch data');
                    }
                })
                .then((data) => {
                    if (data.token === "fail") {
                        setErrorMassage("This UserName is already in use , Please try Another One")
                    } else {
                        setToken(data.token);
                        console.log("token " + data.token);

                        localStorage.setItem('token', data.token);
                        localStorage.setItem('username', username);
                        navigate('/login');
                    }
                })
                .catch((error) => {
                    console.error(error);
                });
        } else {
            alert("Passwords do not match. Please make sure the passwords match.")
        }
    };

    return (
        <Container fluid style={{ backgroundColor: '#f5f5f5', minHeight: '100vh' }}>
            <Row className="justify-content-center align-items-center">
                <Col md={4} style={{marginTop: '15vh'}}>
                    <Alert variant="danger" show={errorMessage !== ''} onClose={() => setErrorMessage('')} dismissible>
                        {errorMessage}
                    </Alert>
                    <Form onSubmit={handleRegistration}>
                        <Form.Group controlId="username">
                            <Form.Label>Username</Form.Label>
                            <Form.Control type="text" value={username} onChange={(e) => setUsername(e.target.value)}
                                          required/>
                        </Form.Group>

                        <Form.Group controlId="email">
                            <Form.Label>Email</Form.Label>
                            <Form.Control type="email" value={email} onChange={(e) => setEmail(e.target.value)}
                                          required/>
                        </Form.Group>

                        <Form.Group controlId="password">
                            <Form.Label>Password</Form.Label>
                            <Form.Control type="password" value={password} onChange={(e) => setPassword(e.target.value)}
                                          required/>
                        </Form.Group>

                        <Form.Group controlId="passwordConfirm">
                            <Form.Label>Confirm Password</Form.Label>
                            <Form.Control type="password" value={passwordConfirm}
                                          onChange={(e) => setPasswordConfirm(e.target.value)} required/>
                        </Form.Group>

                        <Button variant="primary" type="submit" className="mt-3">
                            Register
                        </Button>
                    </Form>
                    <p className="mt-3 text-center">
                        Already have an account?{' '}
                        <Link to={`/login`} style={{color: '#007BFF', textDecoration: 'none'}}>
                            Log In
                        </Link>
                    </p>
                </Col>
            </Row>
        </Container>
    );
}

export default Registration;
